name: unit-testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  maya:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
       include:
         - maya: "2017"
           pip: "2.7/get-pip.py"
         - maya: "2018"
           pip: "2.7/get-pip.py"
         - maya: "2019"
           pip: "2.7/get-pip.py"
         - maya: "2020"
           pip: "2.7/get-pip.py"
         - maya: "2022"
           pip: "get-pip.py"

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Environment
        run: |
          wget https://bootstrap.pypa.io/pip/${{ matrix.pip }}
          mayapy get-pip.py --user
          mayapy -m pip install --user numpy scipy

      - name: Testing
        run: |
          export PYTHONPATH=$(pwd)/scripts
          mayapy ./tests/bin/run.py
